steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/licenta-proiect/backend:$COMMIT_SHA'
      - '-f'
      - 'app/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/licenta-proiect/backend:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'apiredidact'
      - '--image=gcr.io/$PROJECT_ID/github.com/licenta-proiect/backend:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'

images:
  - 'gcr.io/$PROJECT_ID/github.com/licenta-proiect/backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY